// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (User, error)
	DisplayAllUsers(ctx context.Context, arg DisplayAllUsersParams) ([]User, error)
	DisplayUser(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
