// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name
) VALUES (
    $1
) RETURNING id, name, created_at
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const displayAllUsers = `-- name: DisplayAllUsers :many
SELECT id, name, created_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type DisplayAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) DisplayAllUsers(ctx context.Context, arg DisplayAllUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, displayAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const displayUser = `-- name: DisplayUser :one
SELECT id, name, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) DisplayUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, displayUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
